language: emacs-lisp
dist: xenial
env:
  - EMACS=emacs25
before_install:
  - sudo apt-get install -qq autoconf
  - sudo add-apt-repository -y ppa:kelleyk/emacs
  - sudo apt-get update -qq
  - sudo apt-get install -qq $EMACS
script:
  autoconf && ./configure && make
